---
- hosts: 'workers, masters'
  become: yes

  tasks:
    - name: Create the kube user account
      user: name=kube group=kube state=present createhome=yes shell=/bin/bash groups=sudo append=yes

    - name: Allow 'kube' to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: 'kube ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Set up authorized keys for the kube user
      authorized_key: user=kube key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
