- hosts: workers
  become: yes
  gather_facts: yes

  tasks:
    - name: Copy join command from Ansiblehost to the worker nodes.
      become: yes
      copy:
        src: /tmp/kubernetes_join_command
        dest: $HOME/kubernetes_join_command
        mode: 0777

    - name: Join the Worker nodes to the cluster.
      become: yes
      shell: sh $HOME/kubernetes_join_command
      register: joined_or_not
