- hosts: masters
  become: yes
  tasks:
    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=192.168.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Create .kube directory
      become: yes
      become_user: kube
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copies admin.conf to user's kube config
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube















    - name: Get the token for joining the worker nodes
      become: yes
      become_user: kube
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Print debug 
      debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777